## numerical stable

In [11]:
import numpy as np

In [2]:
np.exp(1000) / np.exp(1000)

/Users/liuyanfang/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.
/Users/liuyanfang/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [12]:
# 等价于计算e5 * le-5
test = 0
for i in range(int(1e5)):

    test += 1e-5
print(test)


0.9999999999980838


## InteractiveSession

In [13]:
import tensorflow as tf
sess = tf.InteractiveSession()


In [14]:
hello = tf.constant('hello')
sess.run(hello)

b'hello'

In [15]:
hello.eval()

b'hello'

## softmax 例子

In [8]:
y = [1., 2., 3., 4.]

In [9]:
np.exp(y) / np.sum(np.exp(y))

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [10]:
softmax = tf.nn.softmax(y).eval()
print(softmax)

[0.0320586  0.08714432 0.2368828  0.6439142 ]


In [11]:
tf.argmax(softmax, axis=0).eval()

3

## 损失函数

In [16]:
y_pred = tf.argmax(softmax, axis=0).eval()  # y_pred = 3
real = [1., 0., 0., 0.] # real label 0
loss = tf.nn.softmax_cross_entropy_with_logits(labels=real, logits=y)

NameError: name 'softmax' is not defined

In [13]:
loss.eval()

3.4401898

In [14]:
-np.log(0.0320586)

3.4401898008764813

## 使用TensorFlow内建函数载入MNIST!

In [1]:
import numpy as np


In [2]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('../MNIST_data', one_hot=True)

/Users/liuyanfang/anaconda3/envs/tensorflow1.4/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


Extracting ../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../MNIST_data/t10k-labels-idx1-ubyte.gz


In [21]:
mnist.train.labels[1]


NameError: name 'mnist' is not defined

In [20]:
mnist.train.images[1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [21]:
mnist.train.next_batch(2)

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]))

## Softmax 建模作为练习（20分钟）

placeholder

In [13]:
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

Variable

In [14]:
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

In [15]:
sess=tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

### 练习 1（2分钟）：

线性变换
$y = xW + b$

In [16]:
y = tf.matmul(x, W) + b

计算loss

In [17]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

定义训练步骤

In [18]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

### 练习 2 （5分钟）：
计算正确率，变量命名为 accuracy

In [19]:
softmax_result = tf.nn.softmax(y)
pred = tf.argmax(softmax_result, axis=1)
true = tf.argmax(y_, axis=1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(pred, true), tf.float32))

In [26]:
mnist.train.next_batch(128)


(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

### 练习 3  训练模型（5 分钟）

In [20]:
for i in range(4000):
    batch = mnist.train.next_batch(128)
    _, loss_, acu = sess.run([train_step, loss, accuracy], {x: batch[0], y_: batch[1]})
    if i % 100 == 0:
        print("Step:{:>5}, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(i, loss_, acu))
loss_, acu = sess.run([loss, accuracy], {x: mnist.test.images, 
                                                        y_: mnist.test.labels})
print("Training Finished, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(loss_, acu))

Step:    0, Loss: 2.3026, Accuracy:  7.81%
Step:  100, Loss: 0.5722, Accuracy: 87.50%
Step:  200, Loss: 0.4351, Accuracy: 86.72%
Step:  300, Loss: 0.2649, Accuracy: 91.41%
Step:  400, Loss: 0.2804, Accuracy: 92.97%
Step:  500, Loss: 0.2859, Accuracy: 92.97%
Step:  600, Loss: 0.3123, Accuracy: 91.41%
Step:  700, Loss: 0.3307, Accuracy: 89.84%
Step:  800, Loss: 0.3506, Accuracy: 89.06%
Step:  900, Loss: 0.2090, Accuracy: 93.75%
Step: 1000, Loss: 0.2656, Accuracy: 92.97%
Step: 1100, Loss: 0.1960, Accuracy: 92.19%
Step: 1200, Loss: 0.3611, Accuracy: 92.19%
Step: 1300, Loss: 0.1996, Accuracy: 94.53%
Step: 1400, Loss: 0.4188, Accuracy: 88.28%
Step: 1500, Loss: 0.4101, Accuracy: 90.62%
Step: 1600, Loss: 0.2885, Accuracy: 92.19%
Step: 1700, Loss: 0.3597, Accuracy: 88.28%
Step: 1800, Loss: 0.2644, Accuracy: 92.19%
Step: 1900, Loss: 0.3930, Accuracy: 89.84%
Step: 2000, Loss: 0.2107, Accuracy: 93.75%
Step: 2100, Loss: 0.3641, Accuracy: 90.62%
Step: 2200, Loss: 0.2710, Accuracy: 91.41%
Step: 2300,

## 练习：DNN 建模
* 单隐层
* 激活函数可以使用：
    * tf.nn.relu
    * tf.nn.sigmoid
    * tf.nn.tanh

In [30]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('../MNIST_data/',one_hot=True)

Extracting ../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../MNIST_data/t10k-labels-idx1-ubyte.gz


In [31]:
x=tf.placeholder(tf.float32,shape=[None,784])
y_=tf.placeholder(tf.float32,shape=[None,10])

In [33]:
w=tf.Variable(tf.truncated_normal([784,512],mean=0,stddev=0.1))
b=tf.Variable(tf.zeros([512]))

In [36]:
line_model=tf.matmul(x,w)+b

In [37]:
line_relu=tf.nn.relu(line_model)

In [39]:
w_=tf.Variable(tf.truncated_normal([512,10],mean=0,stddev=0.1))
b_=tf.Variable(tf.zeros([10]))
y=tf.matmul(line_relu,w_)+b_

In [40]:
loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_,logits=y))

In [49]:
opt=tf.train.GradientDescentOptimizer(0.001).minimize(loss)
softmax_y=tf.nn.softmax(y)
pre=tf.argmax(softmax_y,axis=1)
true=tf.argmax(y_,axis=1)
acc=tf.reduce_mean(tf.cast(tf.equal(pre,true),tf.float32))

In [52]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(1000):
        batch=mnist.train.next_batch(128)
        _,l,ac=sess.run([opt,loss,acc],{x:batch[0],y_:batch[1]})
        if i%100:
            print("Step:{:>5}, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(i, l, ac))
    
    t_l,t_ac=sess.run([loss,acc],{x:mnist.test.images,y_:mnist.test.labels})
    print("Loss:{:>7.4f}, Accuracy:{:>7.2%}".format( t_l, t_ac))
    
    

Step:    1, Loss: 2.5811, Accuracy: 17.19%
Step:    2, Loss: 2.5852, Accuracy: 10.94%
Step:    3, Loss: 2.5577, Accuracy: 14.06%
Step:    4, Loss: 2.5246, Accuracy: 11.72%
Step:    5, Loss: 2.6376, Accuracy: 12.50%
Step:    6, Loss: 2.5260, Accuracy: 11.72%
Step:    7, Loss: 2.5320, Accuracy: 10.94%
Step:    8, Loss: 2.5368, Accuracy: 15.62%
Step:    9, Loss: 2.4926, Accuracy: 17.97%
Step:   10, Loss: 2.5432, Accuracy: 12.50%
Step:   11, Loss: 2.4136, Accuracy: 12.50%
Step:   12, Loss: 2.4337, Accuracy: 14.84%
Step:   13, Loss: 2.4765, Accuracy: 12.50%
Step:   14, Loss: 2.3049, Accuracy: 21.88%
Step:   15, Loss: 2.4675, Accuracy: 15.62%
Step:   16, Loss: 2.5824, Accuracy: 11.72%
Step:   17, Loss: 2.5132, Accuracy:  9.38%
Step:   18, Loss: 2.3980, Accuracy: 14.06%
Step:   19, Loss: 2.5379, Accuracy: 13.28%
Step:   20, Loss: 2.3038, Accuracy: 14.06%
Step:   21, Loss: 2.5312, Accuracy: 10.94%
Step:   22, Loss: 2.3740, Accuracy: 13.28%
Step:   23, Loss: 2.3682, Accuracy: 14.84%
Step:   24,

Step:  201, Loss: 1.8721, Accuracy: 36.72%
Step:  202, Loss: 1.8533, Accuracy: 43.75%
Step:  203, Loss: 1.8351, Accuracy: 39.06%
Step:  204, Loss: 1.8678, Accuracy: 36.72%
Step:  205, Loss: 1.7888, Accuracy: 45.31%
Step:  206, Loss: 1.8117, Accuracy: 39.84%
Step:  207, Loss: 1.7467, Accuracy: 40.62%
Step:  208, Loss: 1.8182, Accuracy: 44.53%
Step:  209, Loss: 1.8109, Accuracy: 43.75%
Step:  210, Loss: 1.7329, Accuracy: 46.88%
Step:  211, Loss: 1.8656, Accuracy: 35.16%
Step:  212, Loss: 1.7924, Accuracy: 42.19%
Step:  213, Loss: 1.7581, Accuracy: 41.41%
Step:  214, Loss: 1.8582, Accuracy: 42.97%
Step:  215, Loss: 1.8917, Accuracy: 35.94%
Step:  216, Loss: 1.9615, Accuracy: 32.03%
Step:  217, Loss: 1.8659, Accuracy: 39.84%
Step:  218, Loss: 1.7526, Accuracy: 45.31%
Step:  219, Loss: 1.8698, Accuracy: 39.06%
Step:  220, Loss: 1.6711, Accuracy: 49.22%
Step:  221, Loss: 1.8197, Accuracy: 44.53%
Step:  222, Loss: 1.7443, Accuracy: 42.19%
Step:  223, Loss: 1.8194, Accuracy: 36.72%
Step:  224,

Step:  398, Loss: 1.4132, Accuracy: 58.59%
Step:  399, Loss: 1.5849, Accuracy: 51.56%
Step:  401, Loss: 1.3772, Accuracy: 69.53%
Step:  402, Loss: 1.5949, Accuracy: 53.12%
Step:  403, Loss: 1.5020, Accuracy: 58.59%
Step:  404, Loss: 1.5104, Accuracy: 53.91%
Step:  405, Loss: 1.4509, Accuracy: 55.47%
Step:  406, Loss: 1.4461, Accuracy: 56.25%
Step:  407, Loss: 1.5038, Accuracy: 57.03%
Step:  408, Loss: 1.5216, Accuracy: 50.78%
Step:  409, Loss: 1.5263, Accuracy: 57.03%
Step:  410, Loss: 1.5585, Accuracy: 49.22%
Step:  411, Loss: 1.4514, Accuracy: 60.16%
Step:  412, Loss: 1.5024, Accuracy: 54.69%
Step:  413, Loss: 1.6931, Accuracy: 44.53%
Step:  414, Loss: 1.5152, Accuracy: 53.12%
Step:  415, Loss: 1.6230, Accuracy: 51.56%
Step:  416, Loss: 1.3895, Accuracy: 59.38%
Step:  417, Loss: 1.4106, Accuracy: 62.50%
Step:  418, Loss: 1.4974, Accuracy: 54.69%
Step:  419, Loss: 1.5454, Accuracy: 52.34%
Step:  420, Loss: 1.5145, Accuracy: 55.47%
Step:  421, Loss: 1.4490, Accuracy: 60.94%
Step:  422,

Step:  599, Loss: 1.2551, Accuracy: 71.88%
Step:  601, Loss: 1.4379, Accuracy: 54.69%
Step:  602, Loss: 1.3084, Accuracy: 61.72%
Step:  603, Loss: 1.3367, Accuracy: 63.28%
Step:  604, Loss: 1.3594, Accuracy: 64.06%
Step:  605, Loss: 1.2706, Accuracy: 66.41%
Step:  606, Loss: 1.2464, Accuracy: 67.97%
Step:  607, Loss: 1.1981, Accuracy: 64.84%
Step:  608, Loss: 1.2469, Accuracy: 67.97%
Step:  609, Loss: 1.2827, Accuracy: 64.84%
Step:  610, Loss: 1.4307, Accuracy: 57.81%
Step:  611, Loss: 1.2674, Accuracy: 64.06%
Step:  612, Loss: 1.1961, Accuracy: 67.19%
Step:  613, Loss: 1.2901, Accuracy: 66.41%
Step:  614, Loss: 1.2847, Accuracy: 64.06%
Step:  615, Loss: 1.2434, Accuracy: 66.41%
Step:  616, Loss: 1.3235, Accuracy: 64.06%
Step:  617, Loss: 1.2667, Accuracy: 71.09%
Step:  618, Loss: 1.2871, Accuracy: 67.97%
Step:  619, Loss: 1.1903, Accuracy: 69.53%
Step:  620, Loss: 1.1676, Accuracy: 69.53%
Step:  621, Loss: 1.2947, Accuracy: 64.06%
Step:  622, Loss: 1.2540, Accuracy: 60.94%
Step:  623,

Step:  802, Loss: 1.1014, Accuracy: 72.66%
Step:  803, Loss: 1.1062, Accuracy: 71.88%
Step:  804, Loss: 1.1440, Accuracy: 73.44%
Step:  805, Loss: 1.1734, Accuracy: 67.97%
Step:  806, Loss: 1.0226, Accuracy: 76.56%
Step:  807, Loss: 1.1543, Accuracy: 69.53%
Step:  808, Loss: 1.1527, Accuracy: 72.66%
Step:  809, Loss: 1.2145, Accuracy: 63.28%
Step:  810, Loss: 1.1221, Accuracy: 70.31%
Step:  811, Loss: 1.0425, Accuracy: 75.00%
Step:  812, Loss: 1.1502, Accuracy: 71.88%
Step:  813, Loss: 1.1769, Accuracy: 67.19%
Step:  814, Loss: 1.1154, Accuracy: 70.31%
Step:  815, Loss: 1.2235, Accuracy: 64.06%
Step:  816, Loss: 1.0240, Accuracy: 75.78%
Step:  817, Loss: 1.1764, Accuracy: 64.84%
Step:  818, Loss: 1.1292, Accuracy: 68.75%
Step:  819, Loss: 1.1234, Accuracy: 72.66%
Step:  820, Loss: 1.1561, Accuracy: 66.41%
Step:  821, Loss: 1.0485, Accuracy: 76.56%
Step:  822, Loss: 1.2156, Accuracy: 67.19%
Step:  823, Loss: 1.1256, Accuracy: 75.00%
Step:  824, Loss: 1.1118, Accuracy: 75.00%
Step:  825,

Step:  997, Loss: 1.0316, Accuracy: 75.00%
Step:  998, Loss: 1.1782, Accuracy: 66.41%
Step:  999, Loss: 0.9345, Accuracy: 78.12%
Loss: 0.9994, Accuracy: 73.73%


In [30]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('../MNIST_data', one_hot=True)

Extracting ../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../MNIST_data/t10k-labels-idx1-ubyte.gz


In [31]:
x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

### 构建单层隐藏层

In [32]:
W_h = tf.Variable(tf.truncated_normal([784, 512], mean=0., stddev=0.1))
b_h = tf.Variable(tf.zeros([512]))
h_linear_output = tf.matmul(x, W_h) + b_h

In [33]:
h_output = tf.nn.tanh(h_linear_output)

### 连接全连接层

In [34]:
W = tf.Variable(tf.truncated_normal([512, 10], mean=0., stddev=0.1))
b = tf.Variable(tf.zeros([10]))
y = tf.matmul(h_output, W) + b

### 定义loss

In [35]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

### 使用梯度下降

In [36]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

### 计算正确率

In [37]:
softmax_result = tf.nn.softmax(y)
pred = tf.argmax(softmax_result, axis=1)
true = tf.argmax(y_, axis=1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(pred, true), tf.float32))

### 定义 Session 并且训练模型

In [38]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(5000):
    batch = mnist.train.next_batch(128)
    _, loss_, acu = sess.run([train_step, loss, accuracy], {x: batch[0], y_: batch[1]})
    if i % 100 == 0:
        print("Step:{:>5}, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(i, loss_, acu))
loss_, acu = sess.run([loss, accuracy], {x: mnist.test.images, 
                                                        y_: mnist.test.labels})
print("Training Finished, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(loss_, acu))

Step:    0, Loss: 2.9742, Accuracy: 12.50%
Step:  100, Loss: 0.3540, Accuracy: 89.06%
Step:  200, Loss: 0.2728, Accuracy: 92.97%
Step:  300, Loss: 0.4171, Accuracy: 86.72%
Step:  400, Loss: 0.1956, Accuracy: 94.53%
Step:  500, Loss: 0.0493, Accuracy: 99.22%
Step:  600, Loss: 0.2376, Accuracy: 92.19%
Step:  700, Loss: 0.1439, Accuracy: 96.88%
Step:  800, Loss: 0.1855, Accuracy: 95.31%
Step:  900, Loss: 0.3610, Accuracy: 89.84%
Step: 1000, Loss: 0.0669, Accuracy: 96.88%
Step: 1100, Loss: 0.1723, Accuracy: 96.09%
Step: 1200, Loss: 0.1010, Accuracy: 96.88%
Step: 1300, Loss: 0.0592, Accuracy: 98.44%
Step: 1400, Loss: 0.0949, Accuracy: 96.88%
Step: 1500, Loss: 0.1134, Accuracy: 97.66%
Step: 1600, Loss: 0.1009, Accuracy: 96.88%
Step: 1700, Loss: 0.1958, Accuracy: 95.31%
Step: 1800, Loss: 0.0835, Accuracy: 96.09%
Step: 1900, Loss: 0.0883, Accuracy: 96.88%
Step: 2000, Loss: 0.0627, Accuracy: 97.66%
Step: 2100, Loss: 0.0867, Accuracy: 96.09%
Step: 2200, Loss: 0.0649, Accuracy: 98.44%
Step: 2300,

## tf.layers.dense
[用法](https://tensorflow.google.cn/api_docs/python/tf/layers/dense)

In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('../MNIST_data', one_hot=True)

/Users/liuyanfang/anaconda3/envs/tensorflow1.4/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


Extracting ../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../MNIST_data/t10k-labels-idx1-ubyte.gz


### 练习 构建3层隐藏层 增加validationset(10 分钟):

In [12]:
#定义图
graph=tf.Graph()
with graph.as_default():
    #定义参数
    x = tf.placeholder(tf.float32, shape=[None, 784])
    y_ = tf.placeholder(tf.float32, shape=[None, 10])
    
    #定义模型结构：
    
    layer1=tf.layers.dense(inputs=x,
                           units=512,
                           activation=tf.nn.relu,
                           bias_initializer=tf.constant_initializer(0),
                           kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                          )
    layer2=tf.layers.dense(inputs=layer1,
                           units=128,
                           activation=tf.nn.relu,
                           bias_initializer=tf.constant_initializer(0),
                           kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                          )
    layer3=tf.layers.dense(inputs=layer2,
                           units=512,
                           activation=tf.nn.relu,
                           bias_initializer=tf.constant_initializer(0),
                           kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                          )
    # 分类：
    out=tf.layers.dense(inputs=layer3,
                       units=10,
                       activation=None,
                       bias_initializer=tf.constant_initializer(0),
                       kernel_initializer=tf.truncated_normal_initializer(stddev=0.1))
    # 误差与准确率
    with tf.name_scope('loss'):
        loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_,logits=out))
    opt=tf.train.GradientDescentOptimizer(0.01).minimize(loss)
    out_softmax= tf.nn.softmax(out)
    with tf.name_scope("acc"):
        acc=tf.reduce_mean(tf.cast(tf.equal(tf.argmax(y_,axis=1),tf.argmax(out_softmax,axis=1)),tf.float32))

    tf.summary.scalar('loss',loss)
    tf.summary.scalar('acc',acc)
    

In [19]:
#运行图
with tf.Session(graph=graph) as sess:
    merge=tf.summary.merge_all()
    sess.run(tf.global_variables_initializer())
   
    for i in range(2000):
        batch=mnist.train.next_batch(128)
        _,lo,ac=sess.run([opt,loss,acc],{x:batch[0],y_:batch[1]})
        if i%100==0:
            print("loss={:>5.4f},accuracy={:>5.6f}".format(lo,ac))
    print(sess.run([loss,acc],{x:mnist.test.images,y_:mnist.test.labels}))
        
            
            

loss=2.8779,accuracy=0.039062
loss=0.7595,accuracy=0.812500
loss=0.4861,accuracy=0.875000
loss=0.3919,accuracy=0.882812
loss=0.3963,accuracy=0.906250
loss=0.4097,accuracy=0.875000
loss=0.4014,accuracy=0.875000
loss=0.2159,accuracy=0.937500
loss=0.2837,accuracy=0.921875
loss=0.2049,accuracy=0.953125
loss=0.3587,accuracy=0.890625
loss=0.2642,accuracy=0.937500
loss=0.4592,accuracy=0.882812
loss=0.2054,accuracy=0.953125
loss=0.1369,accuracy=0.968750
loss=0.2605,accuracy=0.929688
loss=0.2592,accuracy=0.937500
loss=0.2547,accuracy=0.914062
loss=0.1493,accuracy=0.960938
loss=0.3157,accuracy=0.906250
[0.20959419, 0.9377]


In [ ]:
layer1 = tf.layers.dense(inputs=x, 
                         units=512, 
                         activation=tf.nn.tanh,                        
                         bias_initializer=tf.constant_initializer(0),
                         kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                        )
layer2 = tf.layers.dense(inputs=layer1, 
                         units=256, 
                         activation=tf.nn.tanh,                        
                         bias_initializer=tf.constant_initializer(0),
                         kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                        )
layer3 = tf.layers.dense(inputs=layer2, 
                         units=128, 
                         activation=tf.nn.tanh,                        
                         bias_initializer=tf.constant_initializer(0),
                         kernel_initializer=tf.truncated_normal_initializer(stddev=0.1)
                        )

全连接层

In [ ]:
y = tf.layers.dense(inputs=layer3, 
                    units=10, 
                    activation=None, 
                    bias_initializer=tf.constant_initializer(0), 
                    kernel_initializer=tf.truncated_normal_initializer(stddev=0.1))

定义loss

In [ ]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

使用梯度下降

In [ ]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)

计算正确率

In [ ]:
softmax_result = tf.nn.softmax(y)
pred = tf.argmax(softmax_result, axis=1)
true = tf.argmax(y_, axis=1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(pred, true), tf.float32))

定义Interactive Session

In [ ]:
sess = tf.InteractiveSession()
init = tf.global_variables_initializer()
sess.run(init)

训练模型

In [ ]:
for i in range(5000):
    batch = mnist.train.next_batch(128)
    _, loss_, acu = sess.run([train_step, loss, accuracy], {x: batch[0], y_: batch[1]})
    if i % 100 == 0:
        print("Step:{:>5}, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(i, loss_, acu))
        loss_, acu = sess.run([loss, accuracy], {x: mnist.validation.images, 
                                                 y_: mnist.validation.labels})
        print("Step:{:>5}, Vali Loss:{:>7.4f}, Vali Accuracy:{:>7.2%}".format(i, loss_, acu))
loss_, acu = sess.run([loss, accuracy], {x: mnist.test.images, 
                                        y_: mnist.test.labels})
print("Training Finished, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(loss_, acu))

## 回顾

In [42]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('../MNIST_data', one_hot=True)

Extracting ../MNIST_data/train-images-idx3-ubyte.gz
Extracting ../MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../MNIST_data/t10k-labels-idx1-ubyte.gz


In [43]:
graph = tf.Graph()
with graph.as_default():
    x = tf.placeholder(tf.float32, shape=[None, 784], name='x')
    y_ = tf.placeholder(tf.float32, shape=[None, 10], name='y')
    with tf.name_scope('hidden_layers'):
        layer1 = tf.layers.dense(inputs=x, 
                                 units=512, 
                                 activation=tf.nn.tanh,                        
                                 bias_initializer=tf.constant_initializer(0),
                                 kernel_initializer=tf.truncated_normal_initializer(stddev=0.1),
                                 name='l1'
                                )
        layer2 = tf.layers.dense(inputs=layer1, 
                                 units=256, 
                                 activation=tf.nn.tanh,                        
                                 bias_initializer=tf.constant_initializer(0),
                                 kernel_initializer=tf.truncated_normal_initializer(stddev=0.1),
                                 name='l2'
                                )
        layer3 = tf.layers.dense(inputs=layer2, 
                                 units=128, 
                                 activation=tf.nn.tanh,                        
                                 bias_initializer=tf.constant_initializer(0),
                                 kernel_initializer=tf.truncated_normal_initializer(stddev=0.1),
                                 name='l3'
                                )
    with tf.name_scope("fully_connected"):
        y = tf.layers.dense(inputs=layer3, 
                            units=10, 
                            activation=None, 
                            bias_initializer=tf.constant_initializer(0), 
                            kernel_initializer=tf.truncated_normal_initializer(stddev=0.1),
                            name='dense'
                           )
    with tf.name_scope("cal_loss"):
        loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))
    with tf.name_scope("train"):
        train_step = tf.train.GradientDescentOptimizer(0.5).minimize(loss)
    with tf.name_scope("cal_accuracy"):
        softmax_result = tf.nn.softmax(y)
        pred = tf.argmax(softmax_result, axis=1)
        true = tf.argmax(y_, axis=1)
        accuracy = tf.reduce_mean(tf.cast(tf.equal(pred, true), tf.float32))
    tf.summary.scalar('loss', loss)
    tf.summary.scalar('accuracy', accuracy)

In [ ]:
with tf.Session(graph=graph) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    merged = tf.summary.merge_all()
    # 定义filewriter
    writer_train = tf.summary.FileWriter('./tmp/train', graph=graph)
    writer_vali = tf.summary.FileWriter('./tmp/vali')
    # 定义saver
    saver = tf.train.Saver()
    for i in range(5000):
        batch = mnist.train.next_batch(128)
        _, mgd = sess.run([train_step, merged], {x:batch[0],
                                                 y_:batch[1]
                                                })
        writer_train.add_summary(mgd, global_step=i)
        mgd = sess.run(merged, {x: mnist.validation.images,
                                              y_: mnist.validation.labels
                                                })
        writer_vali.add_summary(mgd, global_step=i)
    loss_, acu = sess.run([loss, accuracy], {x: mnist.test.images, 
                                            y_: mnist.test.labels})
    print("Training Finished, Loss:{:>7.4f}, Accuracy:{:>7.2%}".format(loss_, acu))
    saver.save(sess, './tmp/model.ckpt')

## 测试模型

In [ ]:
import matplotlib.image as mpimg
import numpy as np
t = mpimg.imread('./test.jpg')
test = np.mean(t, axis=2)

In [ ]:
test = np.reshape(test / 255., 784)

In [ ]:
with tf.Session(graph=graph) as sess:
    saver.restore(sess, './tmp/model.ckpt')
    p = sess.run(pred, {x: [test]})
    print("prediction result{:>2}".format(p[0]))

In [30]:
a=[1,2]
x,y=a


In [31]:
x


1

In [32]:
y

2

In [33]:
[1]

[1]

In [41]:
a=[1]
a += 2,

a

[1, 2]